---
--- Generated by Luanalysis
--- Created by CHEN.
--- DateTime: 2022/10/12 17:37
---

-- 秒杀券 id
local voucherId = ARGV[1]
-- 用户 id
local userId = ARGV[2]
-- 订单 id
local id = ARGV[3]

-- 库存 key
local stockKey = 'seckill:stock:' .. voucherId
-- 订单 key
local orderKey = 'seckill:order:' .. voucherId

-- 库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end

-- 判断用户是否已经下单，禁止重复下单
if (tonumber(redis.call('sismember', orderKey, userId)) == 1) then
    return 2
end

-- 扣减库存
redis.call('incrby', stockKey, -1)
-- 记录用户已下单
redis.call('sadd', orderKey, userId)
-- 发送订单消息到 Redis Stream
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', id)
return 0
